packages:
  - name: kubernetes/kompose@v1.35.0
  - name: kubernetes/kompose
    version: v1.31.0
  - name: kubernetes/kompose
    version: v1.25
  - name: kubernetes/kompose
    version: v1.24.0
  - name: kubernetes/kompose
    version: v1.22.0
  - name: kubernetes/kompose
    version: v1.21.0
  - name: kubernetes/kompose
    version: v1.20.0
  - name: kubernetes/kompose
    version: v1.18.0
  - name: kubernetes/kompose
    version: v0.6.0
  - name: kubernetes/kompose
    version: v0.1.2
