# yaml-language-server: $schema=https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/registry.json
packages:
  - type: github_release
    repo_owner: prometheus
    repo_name: promlens
    description: PromLens – The query builder, analyzer, and explainer for PromQL
    version_constraint: "false"
    version_overrides:
      - version_constraint: "true"
        asset: promlens-{{trimV .Version}}.{{.OS}}-{{.Arch}}.{{.Format}}
        format: tar.gz
        checksum:
          type: github_release
          asset: sha256sums.txt
          algorithm: sha256
